src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[Gedmo\Slug(fields: ['title'])]
    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $slug;

    #[ORM\Column(type: 'text', nullable: true)]
    private $body;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $publishedAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $author;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $likeCount;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageFilename;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private $comments;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'articles')]
    private $tags;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTime
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTime $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(?string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getLikeCount(): ?int
    {
        return $this->likeCount;
    }

    public function setLikeCount(?int $likeCount): self
    {
        $this->likeCount = $likeCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return '/images/' . $this->getImageFilename();
    }

    public function getAuthorAvatarPath()
    {
        return sprintf(
            'https://robohash.org/%s.png?set=set4',
            str_replace(' ', '_', $this->getAuthor())
        );
    }

    public function like()
    {
        $this->likeCount++;

        return $this;
    }

    public function dislike()
    {
        $this->likeCount--;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }
}

templates/about.html.twig
{% extends 'layouts/front.html.twig' %}

{% block content %}
<main>
    <h2>About</h2>
    <p>{{ secret }}</p>
</main>
{% endblock %}

templates/article.html.twig
{% extends 'layouts/front.html.twig' %}

{% block content %}
<main>
    <h2>Articles</h2>
    <div id="div_articles">
    {% for article in articles %}
        <div class="articles_div_article">
            <h4><a href="{{ path('app_article_show', {slug: article.slug }) }}">{{ article.title }}</a></h4>
            {% if article.tags|length %}
                <div>
                    <ul>
                        {% for tag in article.tags %}
                            <li>{{ tag.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div><img class="logo_img" src="{{ asset(article.imagePath) }}" alt="Article image" title="Article image"></div>
            <p>
                <small>author: {{ article.author }}</small>
                <img src="{{ article.authorAvatarPath }}" width="50" height="50">
            </p>
            <p><small>published: {{ article.publishedAt ? article.publishedAt|ago }}</small></p>
        </div>
    {% endfor %}
    </div>
</main>
{% endblock %}
{% block js_footer %}
    {{ parent() }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    <header>
        <h1>My Site</h1>
        <nav>
            <ul>
                <li><a href="{{ path('app_articles') }}">Articles</a></li>
                <li><a href="{{ path('app_about') }}">About</a></li>
                <li><a href="{{ path('app_admin_comments') }}">Comments</a></li>
                <li>&nbsp</li>
                <li><a href="{{ path('app_login') }}">Login</a></li>
                <li><a href="{{ path('app_logout') }}">Logout</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block body %}{% endblock %}
    </main>
    </body>
</html>

templates/base_content.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% block content %}{% endblock %}
{% endblock %}

templates/show.html.twig
{% extends 'layouts/front.html.twig' %}

{% block content %}
<main>
    <h2>Article :: {{ article.title }}
        <i id='ph'
           data-type="like"
           data-like-href="{{ path('app_articles_like', {slug: article.slug, type: 'like'}) }}"
           data-dislike-href="{{ path('app_articles_like', {slug: article.slug, type: 'dislike'}) }}">
            (likes {{ article.likeCount }})
        </i>
    </h2>
    <hr>
    {% if article.tags|length %}
    <div>
        <ul>
            {% for tag in article.tags %}
                <li>{{ tag.name }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <hr>
    <div><img src="{{ asset(article.imagePath) }}" alt="Article image" title="Article image"></div>
    <div>{{ article.body|cached_markdown }}</div>
    <div>
        <p>
            <b>Published at: {{ article.publishedAt ? article.publishedAt|ago : 'not published' }}</b>
        </p>
    </div>
    <div>
        <b>Written By {{ article.author }}</b>
        <img src="{{ article.authorAvatarPath }}" alt="{{ article.author }}" title="{{ article.author }}">
    </div>
    <div>
        <p>Quantity of comments {{ article.nonDeletedComments|length }}</p>
        <ul>
            {% for comment in article.nonDeletedComments %}
                <li>
                    {{ comment.authorName }}: {{ comment.content }} /{{ comment.createdAt|ago }}
                    {% if comment.deletedAt %} DELETED {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>

</main>
{% endblock %}
{% block js_footer %}
    {{ parent() }}
    <script src="http://localhost/{{ asset('js/like.js') }}"></script>
{% endblock %}